services:
  postgres:
    image: postgres:15-alpine
    container_name: tic_tac_boom_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tic_tac_boom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
